name: 'publish-post'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'content/posts/**'

concurrency:
  cancel-in-progress: true
  group: publish-${{ github.head_ref || github.ref }}

jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: blogpub
        uses: protiumx/blogpub@v0.6.0
        with:
          articles_folder: content/posts
          devto_api_key: ${{ secrets.DEVTO_API_KEY }}
          gh_token: ${{ secrets.GH_TOKEN }}
          medium_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          medium_user_id: 10daa8a093e12850dc2d93e0ed846d5dbd14af1fbf5f09b2da4447c0ff1ba3115
